## Array Creation

Write a function array_operation which can accept a parameter l and create a numpy array x, using array method of numpy package then print the following values

The type of array x
Dimensions of x
Shape of x
Size of x
#### Sample Case 
##### Sample Input For Custom Testing
5 10 15 20 25
##### Sample Output
<class 'numpy.ndarray'>
1   
(5,)
5
 

In [2]:
import numpy as np
# Enter your code here. Read input from STDIN. Print output to STDOUT
def array_operations(l):
    #Write your code below
    a = np.array(l)
    print(type(a))
    print(a.ndim)
    print(a.shape)
    print(a.size)
    
if __name__ == "__main__":
    l = list(map(int,input().split()))
    array_operations(l)

5 10 15 20 25
<class 'numpy.ndarray'>
1
(5,)
5


## Determine Attributes
 
Write a function array_attributes which can accept a parameter 2d array as l, then create a numpy array y using array method of numpy package and print the following values

The type of array y

Dimensions of y

Shape of y

Size of y

Type of each data element of y

Number of bytes occupied by each data element of y
 
### Sample Case
#### Sample Input
2

-1 -2 -3 -4

-2 -4 -6 -8

#### Sample Output

<class 'numpy.ndarray'>

2

(2, 4)

8
int32

4

In [3]:
import numpy as np

# Enter your code here. Read input from STDIN. Print output to STDOUTd

def array_attributes(l):
    #write your code here
    a2 = np.array(l)
    print(type(a2))
    print(a2.ndim)
    print(a2.shape)
    print(a2.size)
    print(a2.dtype)
    print(a2.itemsize)
    

if __name__=="__main__":
    r=int(input())
    l=[]
    for i in range(r):
        n = list(map(int,input().split()))
        l.append(n)
    array_attributes(l)

2
1 2 3 5 6 8
4 5 6 8 7 6
<class 'numpy.ndarray'>
2
(2, 6)
12
int32
4


## Array Manipulation

Write a function array_split which can accept three parameters i, r and c, then perform the following operations

- Create a ndarray x having first i natural numbers, using arange method
- Change the shape of x to (c, r) and assign it to new array y
- Split the array y horizontally in to two arrays, then assign it to a and b
- Print a and b

In [ ]:
import numpy as np

# Enter your code here. Read input from STDIN. Print output to STDOUT
def array_split(i,r,c):
    #Write your code below
    a = np.arange(i)
    a.shape = (r, c)
    b, c = np.hsplit(a, 2)
    print(b)
    print(c)

if __name__=="__main__":
    i=int(input())
    r,c = list(map(int,input().split()))
    array_split(i,r,c)

## Array Manipulation 2

#### Function array_split

Write the functions array_split that accepts three numbers n,n_row,n_col  and perform array operations given below

##### Instructions

Create a ndarray x having first n natural numbers, using arange method.

Change the shape of x to (n_row, n_col) and assign it to new array z
Split the array z vertically in to two arrays
Hint : Use vsplit
Print the arrays
 
#### Sample Case 0
#### Sample Input

20
4
5
#### Sample Output

[[0 1 2 3 4]
[5 6 7 8 9]]

[[10 11 12 13 14]
[15 16 17 18 19]]

In [ ]:
import ast
import numpy as np

# Enter your code here. Read input from STDIN. Print output to STDOUT
def array_split(n,n_row,n_col):
    a = np.arange(n)
    a.shape = (n_row,n_col)
    b, c = np.vsplit(a, 2)
    print(b)
    print(c)
    
if __name__ == "__main__":
    n = ast.literal_eval(input())
    n_row = ast.literal_eval(input())
    n_col = ast.literal_eval(input())
    array_split(n,n_row,n_col)

## ndarray

Write a function ndarray to get nd list as a argument array_input, then create a numpy array x1 using array method of numpy package and print the following values

1. Dimensions of x1
2. Shape of x1
3. Size of x1
 

### Input:

The input arrays are already given in the main function
Totally it has 5 nd arrays
Each test case will pass a nd array as a argument to the function ndarray(array_input)

### Sample Input

a
### Sample Output

3
(3, 2, 2)
12

In [4]:
import numpy as np

# Enter your code here. Read input from STDIN. Print output to STDOUT

def ndarray(array_input):
    #Write your code here
    x = np.array(array_input)
    print(x.ndim)
    print(x.shape)
    print(x.size)

if __name__ == "__main__":

    s = input()
    if s == "a":
        array_input = [[[-1, 1], [-2, 2]],
        [[-3, 3], [-4, 4]],
        [[-3, 3], [-4, 4]]]

    elif s == "b":
        array_input = [[[-1, 1], [-2, 2]],
        [[-3, 3], [-4, 4]]]
        
    elif s == "c":
        array_input = [[[-1, 1], [-2, 2], [-2, 2]],
        [[-3, 3], [-4, 4], [-2, 2]],
        [[-1, 1], [-2, 2], [-2, 2]]]

    elif s == "d":
        array_input = [[[[-1, 1], [-2, 2]],
        [[-3, 3], [-4, 4]]],
        [[[-1, 1], [-2, 2]],
        [[-3, 3], [-4, 4]]]]

    elif s == "e":
        array_input = [[[[[-1, 1], [-2, 2]],
        [[-3, 3], [-4, 4]]],
        [[[-1, 1], [-2, 2]],
        [[-3, 3], [-4, 4]]]],
        [[[[-1, 1], [-2, 2]],
        [[-3, 3], [-4, 4]]],
        [[[-1, 1], [-2, 2]],
        [[-3, 3], [-4, 4]]]]]

    ndarray(array_input)

a
3
(3, 2, 2)
12


## ndarray shape
Write a function ndshape which can accepts two arguments d and shape1, than write a code to perform the following

Create a ndarray x1, with the shape d, contains 1's on diagonal and 0's elsewhere 
Create a ndarray x2, with the shape shape1 and contains all 1's
Then, print the values of x1 and x2

#### Sample Case 
#### Sample Input For Custom Testing
3
2 5
####  Sample Output
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

In [5]:
import numpy as np

# Enter your code here. Read input from STDIN. Print output to STDOUT
def multiplyTuple(s):
    x = 1
    for i in s:
        x = x*i
        
    return x
        
def ndshape(d, shape1):
    #Write your code here
    a = np.zeros((d, d))
    np.fill_diagonal(a, 1)  
    print(a)
    
    a = np.ones(multiplyTuple(shape1)).reshape(shape1)
    a.shape = shape1
    print(a)

if __name__ == "__main__":
    d=int(input())
    shape1=list(map(int,input().split()))
    ndshape(d, shape1)

3
2 5
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


## 3D Array
Write a function array_3d which can accept four parameters n, x, y and z, then perform the following

Simulate a random normal distribution for n, whose mean is 5 and standard deviation 2.5. Capture the result in x1.
Find the product of the number of element in the array and the size of one array element in byte. Then store it in the variable A
####  Note: Set numpy random seed value 100

Define a random 3-D array x2 of shape (x, y, z) and of numbers between 0 and 1
Print the value of A and x2

####  Sample Case
####  Sample Input For Custom Testing
20
3 4 2
#### Sample Output
160
[[[0.00568851 0.25242635]
  [0.79566251 0.01525497]
  [0.59884338 0.60380454]
  [0.10514769 0.38194344]]

 [[0.03647606 0.89041156]
  [0.98092086 0.05994199]
  [0.89054594 0.5769015 ]
  [0.74247969 0.63018394]]

 [[0.58184219 0.02043913]
  [0.21002658 0.54468488]
  [0.76911517 0.25069523]
  [0.28589569 0.85239509]]]

In [ ]:
import numpy as np

# Enter your code here. Read input from STDIN. Print output to STDOUT
def array_3d(n, x, y, z):
    #Write your code below
    np.random.seed(100)
    a = np.random.normal(loc=5, scale=2.5, size=n)
    size = a.size*a.itemsize
    print(size)
    
    b = np.random.rand(x, y, z)
    print(b)

if __name__ == "__main__":
    n=int(input())
    x, y, z=list(map(int,input().split()))
    array_3d(n, x, y, z)

## Slicing

Function array_slice

Write the function array_slice which accepts four numbers n, n_dim, n_row, n_col and performs array operations given below.

#### Instructions

Create a array x of shape (n_dim,n_row,n_col) , having first n natural numbers.

Create a boolean array b of shape (2,) , having elements True,False.

Print the values for following expressions

x[b]

x[b,:,1:3]

#### Sample Case 0
#### Sample Input

30
2
3
5 
#### Sample Output

 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]]
[[[ 1  2]
  [ 6  7]
  [11 12]]] 

In [ ]:
import numpy as np

# Enter your code here. Read input from STDIN. Print output to STDOUT
def array_slice(n,n_dim,n_row,n_col):
    x = np.arange(n)
    x.shape = (n_dim, n_row, n_col)
    
    b = np.array([True, False])
    
    print(x[b])
    print(x[b, :, 1:3])
    

if __name__ == '__main__':
    n = int(input())
    n_dim = int(input())
    n_row = int(input())
    n_col = int(input())
    array_slice(n,n_dim,n_row,n_col)

## Array Indexing

Function array_index

Write the function array_index which accepts three numbers n,n_row,n_col and performs the array operations given below.

#### Instructions

Create a array x of shape (n_row,n_col), having first n natural numbers.

Print elements of last row.

Print elements of middle column.

Print elements, overlapping first two rows and last three columns

#### Sample Case 0
#### Sample Input

30
6
5
#### Sample Output

[25 26 27 28 29]
[ 2  7 12 17 22 27]
[[2 3 4]
 [7 8 9]]

In [19]:
import numpy as np

# Enter your code here. Read input from STDIN. Print output to STDOUT
def array_index(n,n_row,n_col):
    x = np.arange(n)
    x.shape = (n_row, n_col)
    print(x[-1])
    c = (n_col-1)//2
    print(x[:, c])
    print(x[:2, n_col-3:])

if __name__ == '__main__':
    n = int(input())
    n_row = int(input())
    n_col = int(input())
    array_index(n,n_row,n_col)

[25 26 27 28 29]
[ 2  7 12 17 22 27]
[[2 3 4]
 [7 8 9]]


## More on ndarray
Write a function arr which can accept four parameters a, x, y and z, then perform the following operations

Define a ndarray x1, having first a even numbers(zero not included)
Hint : Make use of arange
Define a ndarray x2, having equally spaced z numbers between x and y
Hint : Make use of linspace
Print x1 and x2

#### Sample Case
#### Sample Input

41
0 30 15
####  Sample Output

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]
[ 0.          2.14285714  4.28571429  6.42857143  8.57142857 10.71428571
 12.85714286 15.         17.14285714 19.28571429 21.42857143 23.57142857
 25.71428571 27.85714286 30.        ]

In [ ]:
import numpy as np

# Enter your code here. Read input from STDIN. Print output to STDOUT
def arr(a, x, y, z):
    #Write your code here
    a = np.arange(2, a, 2)
    b = np.linspace(x, y, z)    
    print(a)
    print(b)

if __name__ == "__main__":
    a=int(input())
    x, y, z=list(map(int,input().split()))
    arr(a, x, y, z)

## Operations on Arrays 1
#### Function array_oper
Write the function array_oper which accepts two numbers num1,num2 and perform array operations given below.
### Instructions
Create a 2-D array y of shape (2,3) having numbers from num1 to num2

Square each element of y

Add 5 to each element of resulted array.

Print the new array
#### Sample Case 0
##### Sample Input
1
6
##### Sample Output
[[ 6  9 14]
 [21 30 41]]

In [ ]:
import numpy as np

# Enter your code here. Read input from STDIN. Print output to STDOUT
def array_oper(num1,num2):
    a = np.arange(num1, num2+1)
    a.shape = (2,3)
    a = a**2
    a = a+5
    print(a)
    

if __name__ == "__main__":
    num1 = int(input())
    num2 = int(input())
    array_oper(num1,num2)

## Operation on Arrays 2

Function array_oper

Write the function array_oper which accepts two numbers num1,num2 and performs array operations given below.

### Instructions

Create a array x of shape (5,6) , having 30 random integers between num1,num2.
Print the cumulative sum of x along axis 0.
Print the cumulative sum of x along axis 1.
Note : Set np.random.seed(100).
#### Sample Case 0
#### Sample Input
-30
30
#### Sample Output
9
-32

In [ ]:
np.random.seed(100)
x = np.random.randint(num1, num2,30).reshape(5,6)
print(x.cumsum(axis = 0)[-1][-1])
print(x.cumsum(axis = 1)[-1][-1])

## Operation on Arrays 3

##### Function array_oper

Write the function array_oper which accepts three parameters n,m,sd and perform the array operations given below. 

Instructions

Create a array x of shape (n,) , having n random numbers from a normal distribution of mean m and standard deviation sd.

Print mean of x

Print Standard deviation of x

Print variance of x

Note : Set np.random.seed(100)

### Sample Case 0
##### Sample Input
50
10
2
##### Sample Output
9.918398584252099
1.882440098571878
3.543580724711302



In [ ]:
import ast
import numpy as np

# Enter your code here. Read input from STDIN. Print output to STDOUT
def array_oper(n,m,sd):
    np.random.seed(100)
    a = np.random.normal(loc=m, scale=sd, size=n)
    print(np.mean(a))
    print(np.std(a))
    print(np.var(a))
    

if __name__ == '__main__':
    num = ast.literal_eval(input())
    mean = ast.literal_eval(input())
    sd = ast.literal_eval(input())
    array_oper(num,mean,sd)

# Join Arrays
Function join_array

Write the function join_array which accepts two lists - list1,list2 . Function should print the arrays after joining them horizontally.

Instructions

Create a 2-D array p, of shape (2,2)  with elements of list list1
Create a 2-D array q, of shape (2,3)  with elements of list list2
Join the two arrays p and q horizontally
Print the new array
 
#### Sample Case 0
#### Sample Input
[3, 6, 9, 12]
[15, 18, 21, 24, 27, 30]
#### Sample Output\
[[ 3  6 15 18 21]
 [ 9 12 24 27 30]]

In [ ]:
import ast
import numpy as np

# Enter your code here. Read input from STDIN. Print output to STDOUT
def join_array(list1,list2):
    p = np.array(list1)
    p.shape = (2,2)
    q = np.array(list2)
    q.shape = (2,3)
    arr = np.concatenate((p, q), axis=1)
    
    print(arr)
    
if __name__ == "__main__":
    l1 = ast.literal_eval(input())
    l2 = ast.literal_eval(input())
    join_array(l1,l2)