In [1]:
import numpy as np

In [2]:
#version of numpy
print(np.__version__)

1.26.4


In [3]:
np.set_printoptions()

# Creating Array

In [4]:
a = np.array([45,85,65,78,56,2,54])
print(a)

[45 85 65 78 56  2 54]


In [19]:
# Intrinsic Numpy array creation using Numpy method
# np.arange(x) => steps = 1 and excluding x from 0
# np.arange(x, y) => step = 1 and from x to y
# np.arange(x, y, z) => steps = z and from x to y
# np.arange(x, steps=y) => steps = y 

a = np.arange(1, 20, 3)  

print(a)
print(a.size)
print(len(a))
print(a+10-5)

[ 1  4  7 10 13 16 19]
7
7
[ 6  9 12 15 18 21 24]


In [6]:
# Create an array with evenly spaced values.
a = np.linspace(1,21,3)
print(a)

[ 1. 11. 21.]


In [7]:
# Create an array filled with zeros.
x = np.zeros(shape=(2, 4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [18]:
# Create an array filled with ones
x = np.ones(shape=(2, 4, 5))
print(x)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [25]:
# Create an identity matrix.
a = np.eye(4, 5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [10]:
y = np.full(shape=(2,3), fill_value=10.5)
print(y)

[[10.5 10.5 10.5]
 [10.5 10.5 10.5]]


## Random 

In [11]:
# 5 random numbers between 0 and 1
np.random.seed(100)
a = np.random.rand(5)

print(a)

[0.54340494 0.27836939 0.42451759 0.84477613 0.00471886]


In [19]:
# 3 random integers between 10 and 50
np.random.seed(100) 
a = np.random.randint(10, 50, 3) 

print(a)

[18 34 13]


In [39]:
# create a new array of a given shape and type, without initializing the entries. 
# This means the values in the array are random and depend on the state of the memory.  
a = np.empty((10, 10), dtype=np.int8, order='C')
print(a)

[[-56 -32 -16  87 -90   2   0   0  64   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0  51   0   0   0]
 [ 50  55 100  55  55  98  53  53  55  50]
 [100  50  49  48 101  52  48 101  97  49]
 [ 48 101  52  57  51  54  53  52  51  55]
 [ 48  98  49 100  57 100  49  54  48  54]
 [ 52  52  50 102  99  50  54  50  50  48]
 [ 57 101  55  50  97 101  52  48  97  54]]


In [40]:
# Standard Normal distribution
np.random.seed(100)
a = np.random.randn(3) 

print(a)

[-1.74976547  0.3426804   1.1530358 ]


In [41]:
# Standard Binomial distribution
# Number of trials, probability of each trial
n, p = 5, .5  

# Result of flipping a coin 10 times, tested 1000 times.
a = np.random.binomial(n, p, 100)

print(a)

[0 1 3 4 1 3 4 2 1 1 2 5 3 1 4 2 2 4 4 2 1 2 0 2 3 0 3 3 1 2 1 4 5 1 4 3 3
 3 3 0 2 3 3 2 2 4 5 4 2 3 2 2 1 2 1 3 2 3 3 1 4 4 3 2 2 2 2 2 1 4 4 3 3 2
 1 2 3 1 3 5 2 2 3 3 2 3 3 2 1 2 2 3 2 3 2 3 3 3 3 2]


In [42]:
# normal distribution with mean 10 and sd 2
np.random.seed(100)
a = 10 + 2*np.random.randn(3) 

print(a)

[ 6.50046905 10.68536081 12.30607161]


## Reading Data From File

In [13]:
from io import StringIO
import numpy as np

x = StringIO('''88.25 93.45 72.60 90.90
72.3 78.85 92.15 65.75
90.5 92.45 89.25 94.50
''')

d = np.loadtxt(x, delimiter=' ')

print(d)

print(d.ndim, d.shape)

[[88.25 93.45 72.6  90.9 ]
 [72.3  78.85 92.15 65.75]
 [90.5  92.45 89.25 94.5 ]]
2 (3, 4)


## Numpy Data Types 
numpy.bool_

numpy.ubyte

numpy.short

numpy.ushort = unsigned short

numpy.int_ = long

numpy.intc

numpy.uintc

numpy.longlong = long long

numpy.ulonglong

numpy.half / numpy.float16

numpy.single

numpy.double

numpy.longdouble

numpy.csingle = complex float

numpy.cdouble

numpy.clongdouble

#### Can assign 8, 16, 32, 64 etc after data type as follows

In [14]:
# 1D array
d = np.zeros(10, dtype=np.int64)
print("\n 1D array \n", d)

# 2D array
d2 = np.zeros([4,3])
print("\n 2D array \n", d2)

# 3D array
d3 = np.zeros([3,3,3])
print("\n 3D array \n", d3)


 1D array 
 [0 0 0 0 0 0 0 0 0 0]

 2D array 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 3D array 
 [[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


# Operations

In [7]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr+10)
print(arr-10)
print(arr*10)
print(arr/10)
print(arr//10)

[11 12 13 14 15 16 17 18 19 20]
[-9 -8 -7 -6 -5 -4 -3 -2 -1  0]
[ 10  20  30  40  50  60  70  80  90 100]
[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
[0 0 0 0 0 0 0 0 0 1]


# Single Elements

In [27]:
arr = np.array([15,23,64,98,25,78,43])

# Accessing by index
print(arr[3])

# Assigning the element at index
arr[3] = 1000
print(arr[3])

# Accessing by reverse indexing
print(arr[-1])

# Size of array
print(arr.size)

98
1000
43
7


# Shape and Size 

#### ndarray.ndim(), ndarray.size(), ndarray.shape()

In [13]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

a.ndim

2

In [14]:
a.shape

(3, 4)

In [15]:
a.size

12

# Reshape & Flatten

In [16]:
a = np.arange(1,25)
a.reshape(8,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [17]:
a.reshape(2,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [19]:
a.reshape( 2, 2, 6)

array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]],

       [[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]]])

In [54]:
np.random.seed(100)
x = np.random.randint(10, 100, 8)
print(x, end='\n\n')

# Reshape an array
y = x.reshape(2,4)
print(y, end='\n\n')

z = x.reshape(2,2,2)
print(z, '\n\n')

# Flatten a multi-dimensional array into a one-dimensional array.
a = z.flatten()
print(a)

[18 34 77 97 89 58 20 62]

[[18 34 77 97]
 [89 58 20 62]]

[[[18 34]
  [77 97]]

 [[89 58]
  [20 62]]] 


[18 34 77 97 89 58 20 62]


### Concatenate

In [ ]:
# Concatenate arrays.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concatenated_arr = np.concatenate((arr1, arr2))

## Stacking Array with vstack and hstack Methods

In [28]:
x = np.array([[-1, 1], [-3, 3]])
y = np.array([[-2, 2], [-4, 4]])
np.vstack((x,y))

array([[-1,  1],
       [-3,  3],
       [-2,  2],
       [-4,  4]])

In [29]:
x = np.array([[-1, 1], [-3, 3]])
y = np.array([[-2, 2], [-4, 4]])
z = np.array([[-5, 5], [-6, 6]])
np.hstack((x,y,z))

array([[-1,  1, -2,  2, -5,  5],
       [-3,  3, -4,  4, -6,  6]])

## Splitting Arrays vertically vsplit  method

In [30]:
# vsplit
x = np.arange(30).reshape(6, 5)
res = np.vsplit(x, 2)

print(res[0], end='\n\n')
print(res[1])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

[[15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


## Splitting Arrays Horizontally hsplit method

In [53]:
# 1D Array
a = np.arange(9)
split_a = np.split(a, 3)

print(a)
print(split_a, end="\n\n")

# 2D Array
a = np.arange(9).reshape(3, 3)
split_a = np.split(a, 3)

print(a)
print(split_a, end="\n\n")

# 3D Array
a = np.arange(27).reshape(3, 3, 3)
split_a = np.split(a, 3)

print(a)
print(split_a, end="\n\n")

[0 1 2 3 4 5 6 7 8]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]]), array([[[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]]), array([[[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])]



In [66]:
x = np.arange(10).reshape(2, 5)
res = np.hsplit(x, (2,4))

print(x, end='\n\n')
print(res, end='\n\n')
print(res[0], end='\n\n')
print(res[1], end='\n\n')
print(res[2])


[[0 1 2 3 4]
 [5 6 7 8 9]]

[array([[0, 1],
       [5, 6]]), array([[2, 3],
       [7, 8]]), array([[4],
       [9]])]

[[0 1]
 [5 6]]

[[2 3]
 [7 8]]

[[4]
 [9]]


# Creating Matrices

### 2D Array

In [29]:
matrix = np.arange(9)
matrix.shape = (3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [30]:
matrix = np.arange(12)
matrix.shape = (2,2,3)
matrix

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

### Slicing and Indexing

In [53]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

In [54]:
a[1,1]

6

In [59]:
a[0:2,2]

array([3, 7])

In [58]:
a[0,1:3]

array([2, 3])

In [41]:
y = np.array([[0, 1, 2],
              [3, 4, 5]])
print(y[1:2, 1:3]) 
print(y[1])   
print(y[:, 1]) 

[[4 5]]
[3 4 5]
[1 4]


In [42]:
# For slicing an n dimensional ndarray, n slice objects are required.
z = np.array([[[-1, 1], [-2, 2]],
              [[-4, 4], [-5, 5]],
              [[-7, 7], [-9, 9]]])
print(z[1,:,1]) # index 1 element in row of index 1
print(z[1:,1,:]) # From all outer rows except the first, select 1st index element (which itself is an array) completely.
print(z[2]) # print 2nd index element

[4 5]
[[-5  5]
 [-9  9]]
[[-7  7]
 [-9  9]]


### Aggregation

In [75]:
a = np.array([[ 12,  25,  83,  14],
              [ 45,  61,  17,  38],
              [ 69,  10,  11,  12],
              [ 13,  14,  15,  16]])

In [76]:
a.min()

10

In [77]:
a.max()

83

In [78]:
a.sum()

455

In [80]:
a.min(axis=0)

array([12, 10, 11, 12])

In [83]:
a.min(axis=1)

array([12, 17, 10, 13])

In [84]:
a.max(axis=0)

array([69, 61, 83, 38])

In [85]:
a.max(axis=1)

array([83, 61, 69, 16])

# Views and Copies

In [33]:
cat = np.array([12,13,14,15])
dog = cat

#changing the element
dog[0] = 123

# printing the array
print(cat)
print(dog)

#changing the element
dog.shape = (2,2)
dog[1]  = 122334

# printing the array
print(cat)
print(dog)

#printing ids
print(id(dog))
print(id(cat))

[123  13  14  15]
[123  13  14  15]
[[   123     13]
 [122334 122334]]
[[   123     13]
 [122334 122334]]
1929969235792
1929969235792


# Deep Copy

In [31]:
cat = np.array([12,13,14,15])
dog = np.copy(cat)

#changing the element
dog[0] = 123

# printing the array
print(cat)
print(dog)

#changing the element
dog.shape = (2,2)
dog[1]  = 122334

# printing the array
print(cat)
print(dog)

#printing ids
print(id(dog))
print(id(cat))

[12 13 14 15]
[123  13  14  15]
[12 13 14 15]
[[   123     13]
 [122334 122334]]
1929969237424
1929969236656


# Shallow Copy

In [32]:
cat = np.array([12,13,14,15])
dog = cat.view()
dog[0] = 123

#changing the element
dog[0] = 123

# printing the array
print(cat)
print(dog)

#changing the element
dog.shape = (2,2)
dog[1]  = 122334

# printing the array
print(cat)
print(dog)

#printing ids
print(id(dog))
print(id(cat))

[123  13  14  15]
[123  13  14  15]
[   123     13 122334 122334]
[[   123     13]
 [122334 122334]]
1929969236656
1929969235408


# Array Attributes

In [5]:
a = np.array([1,2,3,4,5,6,7,8,9])
a.shape = (3,3)

In [6]:
a.shape

(3, 3)

In [7]:
a.ndim

2

In [8]:
a.size

9

In [9]:
a.dtype

dtype('int32')

In [10]:
a.itemsize

4

In [11]:
type(a)

numpy.ndarray

In [12]:
a.nbytes

36

## Iterating through Numpy Array

In [43]:
x = np.array([[0,1], [2, 3]])
for a in np.nditer(x):
    print(a)

0
1
2
3


In [46]:
x = np.arange(30).reshape(3,5,2)
print(x[1][::2][1])

[14 15]


In [47]:

x = np.arange(4)
print(x.flatten())

[0 1 2 3]


In [48]:
x = np.arange(30).reshape(3,5,2)
print(x[1,::2,1])

[11 15 19]


In [49]:
x = np.arange(4).reshape(2,2)
print(x.tolist())

[[0, 1], [2, 3]]


In [51]:
print(np.array(([1, 2], (3,4))).shape)

(2, 2)


In [52]:
x = np.arange(30).reshape(3,5,2)
print(x[1,::2,1])

[11 15 19]


In [53]:
x = np.array([[-2], 
              [2]])
y = np.array([[-3, 3]])
print(x + y)

[[-5  1]
 [-1  5]]


In [54]:
y = np.array([3+4j, 0.4+7.8j])
print(y.dtype)

complex128


In [56]:
x = np.arange(20).reshape(4, 5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [57]:
x = np.arange(6).reshape(2,3)

y = np.hsplit(x,(2,))
print(y[0])

[[0 1]
 [3 4]]


In [58]:
x = np.arange(12).reshape(3,4)
print(x[:,1])

[1 5 9]


In [59]:
x = np.arange(12).reshape(3,4)
print(x[-1:,].shape)

(1, 4)


In [60]:
print(np.repeat(3, 4))

[3 3 3 3]


In [61]:
x = np.arange(4)
y = np.arange(4)

print(x == y)

[ True  True  True  True]


In [62]:
x = np.arange(30).reshape(3,5,2)
print(x[1][::2][1])

[14 15]


In [63]:
x = np.array([[-2], 
              [2]])

y = np.array([[-3, 3]])

print(x.dot(y))

[[ 6 -6]
 [-6  6]]
