## Statistics

In [17]:
%matplotlib inline
import scipy as sp
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm


### Sample data

In [18]:
num_point = 10000
random_data = sp.randn(num_point)
type(random_data)

C:\Users\Shubham\AppData\Local\Temp/ipykernel_20536/690767635.py:2: DeprecationWarning: scipy.randn is deprecated and will be removed in SciPy 2.0.0, use numpy.random.randn instead
  random_data = sp.randn(num_point)


numpy.ndarray

In [19]:
random_data.mean()

0.0023868931867168756

In [20]:
sp.median(random_data)

C:\Users\Shubham\AppData\Local\Temp/ipykernel_20536/3466388688.py:1: DeprecationWarning: scipy.median is deprecated and will be removed in SciPy 2.0.0, use numpy.median instead
  sp.median(random_data)


0.018952877023887205

In [21]:
min_max = np.array([random_data.min(), random_data.max()])
min_max

array([-3.64927456,  4.74045864])

In [22]:
spread_measures = np.array([sp.std(random_data), sp.var(random_data)])
spread_measures

C:\Users\Shubham\AppData\Local\Temp/ipykernel_20536/2576976130.py:1: DeprecationWarning: scipy.std is deprecated and will be removed in SciPy 2.0.0, use numpy.std instead
  spread_measures = np.array([sp.std(random_data), sp.var(random_data)])
C:\Users\Shubham\AppData\Local\Temp/ipykernel_20536/2576976130.py:1: DeprecationWarning: scipy.var is deprecated and will be removed in SciPy 2.0.0, use numpy.var instead
  spread_measures = np.array([sp.std(random_data), sp.var(random_data)])


array([0.99396042, 0.98795733])

In [23]:
sp.stats.describe(random_data)

DescribeResult(nobs=10000, minmax=(-3.649274562872775, 4.7404586355930975), mean=0.0023868931867168756, variance=0.9880561307998253, skewness=-0.0015049589547170813, kurtosis=0.045688129319427784)

## Probability

In [ ]:
iq_mean = 100
iq_std_dev = 15


## Basic Operations with Scalars

In [2]:
import numpy as np
x = np.arange(6).reshape(2,3)
print(x + 10, end='\n\n')
print(x * 3, end='\n\n')
print(x % 2)

[[10 11 12]
 [13 14 15]]

[[ 0  3  6]
 [ 9 12 15]]

[[0 1 0]
 [1 0 1]]


## Basic Operations between Arrays

In [3]:
x = np.array([[-1, 1], [-2, 2]])
y = np.array([[4, -4], [5, -5]])
print(x + y, end='\n\n')
print(x * y)

[[ 3 -3]
 [ 3 -3]]

[[ -4  -4]
 [-10 -10]]


In [4]:
x = np.array([[-1, 1], [-2, 2]])
y = np.array([-10, 10])
print(x * y)

[[10 10]
 [20 20]]


## Broadcasting in NumPy
- Element wise operations between arrays are possible only when they have the same shape or compatible for Broadcasting.

- Steps followed to verify the feasibility of Broadcasting between arrays are:

Initially, compare the dimensions of all arrays.

1. If dimensions do not match, prepend 1's to shape of a smaller array so that it matches dimensions of a larger array.

2. Start comparing array shapes from the last dimension and move backward.

4. If the shape of both arrays are equal or either of it has a shape of 1, continue the comparison.

5. Else at any dimension, if step 4 fails, broadcasting between arrays is not feasible.

- Finally, the resulted broadcasting array shape would be maximum of two compared shapes in each dimension.

In [5]:
x = np.array([[0,1], [2,3]])
print(np.square(x), end='\n\n')
print(np.sin(x))

[[0 1]
 [4 9]]

[[0.         0.84147098]
 [0.90929743 0.14112001]]


In [6]:
x = np.array([[0,1], [2, 3]])
print(x.sum(), end='\n\n')
print(x.sum(axis=0), end='\n\n')
print(x.sum(axis=1))

6

[2 4]

[1 5]


## NumPy Array Methods
- Many of the universal functions are available as methods of ndarray class.

- By default sum method adds all array elements.

- It is also possible to apply sum method on elements of a specific dimension, using axis argument.

In [7]:
x = np.array([[0,1], [2, 3]])

print(x.sum(), end='\n\n')
print(x.sum(axis=0), end='\n\n')
print(x.sum(axis=1))

6

[2 4]

[1 5]


## Linear Algebra

In [8]:
# matrix
matrix = np.matrix([[1,2,3], [4,5,6], [7,8,9]])
matrix

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [9]:
# transpose
matrix.T

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [10]:
# inverse
matrix.I

matrix([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
        [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
        [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [11]:
# multiplication of inverse
matrix*matrix.I

matrix([[ 0. ,  1. , -0.5],
        [ 0. ,  2. , -1. ],
        [ 0. ,  3. ,  2.5]])

In [12]:
# unit matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
## Solving simultanous linear equations
right_hand_side = np.matrix([[11], 
                             [22], 
                             [33]]
                           )

inverse = matrix.I
solution = inverse*right_hand_side
solution

matrix([[ 48.],
        [-32.],
        [ 16.]])

In [14]:
matrix*solution - right_hand_side

matrix([[ 21.],
        [106.],
        [191.]])

In [15]:
#more effiecient for large matrices
from numpy.linalg import solve
solve(matrix, right_hand_side)

matrix([[-3.26666667],
        [ 6.53333333],
        [ 0.4       ]])

In [16]:
#compute the eigen value and right egienvectors
from numpy.linalg import eig
eig(matrix)

(array([ 1.61168440e+01, -1.11684397e+00, -3.38433605e-16]),
 matrix([[-0.23197069, -0.78583024,  0.40824829],
         [-0.52532209, -0.08675134, -0.81649658],
         [-0.8186735 ,  0.61232756,  0.40824829]]))